`timescale 1ns/1ps

module tb_FFT_16Point();

    // Clock and Reset Signals
    reg clk, rst_n;
    reg enable;

    // 16 Real Input Signals
    reg signed [15:0] x0_r,  x1_r,  x2_r,  x3_r,  x4_r,  x5_r,  x6_r,  x7_r;
    reg signed [15:0] x8_r,  x9_r,  x10_r, x11_r, x12_r, x13_r, x14_r, x15_r;

    // 16 Real Output Wires
    wire signed [15:0] X0_r,  X1_r,  X2_r,  X3_r,  X4_r,  X5_r,  X6_r,  X7_r;
    wire signed [15:0] X8_r,  X9_r,  X10_r, X11_r, X12_r, X13_r, X14_r, X15_r;

    // 16 Imaginary Output Wires
    wire signed [15:0] X0_i,  X1_i,  X2_i,  X3_i,  X4_i,  X5_i,  X6_i,  X7_i;
    wire signed [15:0] X8_i,  X9_i,  X10_i, X11_i, X12_i, X13_i, X14_i, X15_i;

    // Memory array for input file & file handle for output
    reg [15:0] inputs [0:15];
    integer file_out;
    integer i;

    // =========================================================================
    // Instantiate Top 16-Point FFT Module
    // =========================================================================
    FFT_16Point uut (
        .clk(clk), .rst_n(rst_n), .enable(enable),
        
        .x0_r(x0_r),   .x1_r(x1_r),   .x2_r(x2_r),   .x3_r(x3_r),
        .x4_r(x4_r),   .x5_r(x5_r),   .x6_r(x6_r),   .x7_r(x7_r),
        .x8_r(x8_r),   .x9_r(x9_r),   .x10_r(x10_r), .x11_r(x11_r),
        .x12_r(x12_r), .x13_r(x13_r), .x14_r(x14_r), .x15_r(x15_r),

        .X0_r(X0_r),   .X1_r(X1_r),   .X2_r(X2_r),   .X3_r(X3_r),
        .X4_r(X4_r),   .X5_r(X5_r),   .X6_r(X6_r),   .X7_r(X7_r),
        .X8_r(X8_r),   .X9_r(X9_r),   .X10_r(X10_r), .X11_r(X11_r),
        .X12_r(X12_r), .X13_r(X13_r), .X14_r(X14_r), .X15_r(X15_r),

        .X0_i(X0_i),   .X1_i(X1_i),   .X2_i(X2_i),   .X3_i(X3_i),
        .X4_i(X4_i),   .X5_i(X5_i),   .X6_i(X6_i),   .X7_i(X7_i),
        .X8_i(X8_i),   .X9_i(X9_i),   .X10_i(X10_i), .X11_i(X11_i),
        .X12_i(X12_i), .X13_i(X13_i), .X14_i(X14_i), .X15_i(X15_i)
    );

    // Clock Generation (Period = 10ns)
    always #5 clk = ~clk;

    // =========================================================================
    // Main Test Stimulus Sequence
    // =========================================================================
    initial begin
        // Initialize Signals
        clk = 0; rst_n = 0;
        x0_r = 0; x1_r = 0; x2_r = 0; x3_r = 0;
        x4_r = 0; x5_r = 0; x6_r = 0; x7_r = 0;
        x8_r = 0; x9_r = 0; x10_r = 0; x11_r = 0;
        x12_r = 0; x13_r = 0; x14_r = 0; x15_r = 0;

        // Load hex file generated by MATLAB STEP 1
        $readmemh("fft16_inputs.hex", inputs);
        
        #20; 
        rst_n = 1; // Release Reset
        enable = 1;
        // -------------------------------------------------------------
        // STEP 1: Apply Inputs at Clock Edge
        // -------------------------------------------------------------
        @(posedge clk);
        #1;
        x0_r  = inputs[0];  x1_r  = inputs[1];  x2_r  = inputs[2];  x3_r  = inputs[3];
        x4_r  = inputs[4];  x5_r  = inputs[5];  x6_r  = inputs[6];  x7_r  = inputs[7];
        x8_r  = inputs[8];  x9_r  = inputs[9];  x10_r = inputs[10]; x11_r = inputs[11];
        x12_r = inputs[12]; x13_r = inputs[13]; x14_r = inputs[14]; x15_r = inputs[15];

        $display("\n=======================================================");
        $display("          16-POINT FFT DEBUG MONITOR CONSOLE           ");
        $display("=======================================================");
        $display("[TIME %0t ns] Inputs Applied:", $time);
        $display("x0..x7  : %04X %04X %04X %04X %04X %04X %04X %04X", 
                 x0_r, x1_r, x2_r, x3_r, x4_r, x5_r, x6_r, x7_r);
        $display("x8..x15 : %04X %04X %04X %04X %04X %04X %04X %04X\n", 
                 x8_r, x9_r, x10_r, x11_r, x12_r, x13_r, x14_r, x15_r);

        // Wait 4 Clock Cycles for 4 Pipelined Stages to settle
        repeat(4) @(posedge clk);
        #1;

        // -------------------------------------------------------------
        // STEP 2: Display Final Settled Outputs
        // -------------------------------------------------------------
        $display("[TIME %0t ns] FINAL SETTLED OUTPUTS (Real | Imag):", $time);
        $display("X0  = %04X %04X", X0_r,  X0_i);
        $display("X1  = %04X %04X", X1_r,  X1_i);
        $display("X2  = %04X %04X", X2_r,  X2_i);
        $display("X3  = %04X %04X", X3_r,  X3_i);
        $display("X4  = %04X %04X", X4_r,  X4_i);
        $display("X5  = %04X %04X", X5_r,  X5_i);
        $display("X6  = %04X %04X", X6_r,  X6_i);
        $display("X7  = %04X %04X", X7_r,  X7_i);
        $display("X8  = %04X %04X", X8_r,  X8_i);
        $display("X9  = %04X %04X", X9_r,  X9_i);
        $display("X10 = %04X %04X", X10_r, X10_i);
        $display("X11 = %04X %04X", X11_r, X11_i);
        $display("X12 = %04X %04X", X12_r, X12_i);
        $display("X13 = %04X %04X", X13_r, X13_i);
        $display("X14 = %04X %04X", X14_r, X14_i);
        $display("X15 = %04X %04X", X15_r, X15_i);
        $display("=======================================================\n");

        // Write to Output Hex File for MATLAB
        file_out = $fopen("fft16_rtl_outputs.hex", "w");
        $fdisplay(file_out, "%04X %04X", X0_r,  X0_i);
        $fdisplay(file_out, "%04X %04X", X1_r,  X1_i);
        $fdisplay(file_out, "%04X %04X", X2_r,  X2_i);
        $fdisplay(file_out, "%04X %04X", X3_r,  X3_i);
        $fdisplay(file_out, "%04X %04X", X4_r,  X4_i);
        $fdisplay(file_out, "%04X %04X", X5_r,  X5_i);
        $fdisplay(file_out, "%04X %04X", X6_r,  X6_i);
        $fdisplay(file_out, "%04X %04X", X7_r,  X7_i);
        $fdisplay(file_out, "%04X %04X", X8_r,  X8_i);
        $fdisplay(file_out, "%04X %04X", X9_r,  X9_i);
        $fdisplay(file_out, "%04X %04X", X10_r, X10_i);
        $fdisplay(file_out, "%04X %04X", X11_r, X11_i);
        $fdisplay(file_out, "%04X %04X", X12_r, X12_i);
        $fdisplay(file_out, "%04X %04X", X13_r, X13_i);
        $fdisplay(file_out, "%04X %04X", X14_r, X14_i);
        $fdisplay(file_out, "%04X %04X", X15_r, X15_i);
        $fclose(file_out);

        $finish;
    end

endmodule