% =========================================================================
% 8-Point Fixed-Point Real-Input FFT: System Model & RTL Plotter
% Format: 16-bit Q1.14 Fixed-Point (SCALE = 2^14 = 16384)
% Input: Sine Wave with Amplitude = 0.3
% =========================================================================
clear; clc; close all;

SCALE = 2^14; % Q1.14 scale factor (16384)

% =========================================================================
% STEP 1: Generate Sine Wave Input & Write 'fft_inputs.hex'
% =========================================================================
N = 8;
amp = 0.3;                             % Amplitude = 0.3
n = 0:N-1;
x_float = amp * sin(2 * pi * n / N);   % Sine wave input generation

% Quantize input to Q1.14 signed 16-bit integer
x_fixed = int16(round(x_float * SCALE)); 

fid_in = fopen('fft_inputs.hex', 'w');
if fid_in == -1, error('Cannot open fft_inputs.hex'); end

% typecast converts int16 to uint16 directly keeping proper 2's complement
x_uint = typecast(x_fixed, 'uint16');

for k = 1:8
    fprintf(fid_in, '%04X\n', x_uint(k));
end
fclose(fid_in);
disp('[STEP 1 DONE] Generated 0.3 Amplitude Sine Wave in fft_inputs.hex.');

% =========================================================================
% STEP 2: Compute MATLAB System Model (Matrix DFT + Hardware Scaling)
% =========================================================================
k_idx = n';
W_matrix = exp(-1i * 2 * pi * k_idx * n / N); % Ideal 8-point DFT matrix

% System level computation (Ideal floating-point DFT)
X_ideal = (double(x_fixed) / SCALE) * W_matrix;

% Apply overall pipeline hardware scaling (1/2 per stage x 3 stages = 1/8)
X_scaled = X_ideal / 8;

% System Model Real and Imaginary floating values
matlab_r = real(X_scaled);
matlab_i = imag(X_scaled);

% Quantize MATLAB Golden Model outputs to Q1.14
X_sys_r_q = int16(round(matlab_r * SCALE));
X_sys_i_q = int16(round(matlab_i * SCALE));

% Export Golden Reference hex file for comparison
fid_gold = fopen('fft_golden_outputs.hex', 'w');
for m = 1:N
    fprintf(fid_gold, '%04X %04X\n', uint16(X_sys_r_q(m)), uint16(X_sys_i_q(m)));
end
fclose(fid_gold);
disp('[STEP 2 DONE] Computed System Model & exported fft_golden_outputs.hex.');

% =========================================================================
% STEP 3: Read Verilog RTL Simulation Results ('fft_rtl_outputs.hex')
% =========================================================================
fid_rtl = fopen('fft_rtl_outputs.hex', 'r');

if fid_rtl == -1
    fprintf('\n-----------------------------------------------------------------\n');
    fprintf(' [NOTICE] fft_rtl_outputs.hex not found in current folder!\n');
    fprintf(' Next Action: Run your Verilog Simulation in ModelSim/Vivado now.\n');
    fprintf(' Once simulation finishes, run this script again to plot results.\n');
    fprintf('-----------------------------------------------------------------\n');
    return; % Stop here until RTL simulation produces output file
end

% Read hex output generated by Verilog $fdisplay
rtl_raw = fscanf(fid_rtl, '%x %x', [2 8])';
fclose(fid_rtl);

% Convert 16-bit hex values back to Q1.14 floating values
rtl_r = double(typecast(uint16(rtl_raw(:, 1)), 'int16')) / SCALE;
rtl_i = double(typecast(uint16(rtl_raw(:, 2)), 'int16')) / SCALE;

disp('[STEP 3 DONE] Successfully loaded Verilog RTL outputs.');

% =========================================================================
% STEP 4: Plot System Model vs. Verilog RTL Output
% =========================================================================
bins = 0:7;
figure('Name', '8-Point FFT: Sine Wave Input (Amp=0.3)', 'Color', 'w');

% --- Real Part Plot ---
subplot(3, 1, 1);
stem(bins, matlab_r, 'bo-', 'LineWidth', 1.5, 'MarkerSize', 8, 'DisplayName', 'MATLAB Model');
hold on;
stem(bins, rtl_r, 'r*--', 'LineWidth', 1.2, 'MarkerSize', 8, 'DisplayName', 'Verilog RTL');
grid on; ylabel('Real Part');
title('Real Part: MATLAB System Model vs RTL Output');
legend('Location', 'best'); xlim([-0.5 7.5]);

% --- Imaginary Part Plot ---
subplot(3, 1, 2);
stem(bins, matlab_i, 'bo-', 'LineWidth', 1.5, 'MarkerSize', 8, 'DisplayName', 'MATLAB Model');
hold on;
stem(bins, rtl_i, 'r*--', 'LineWidth', 1.2, 'MarkerSize', 8, 'DisplayName', 'Verilog RTL');
grid on; ylabel('Imag Part');
title('Imaginary Part: MATLAB System Model vs RTL Output');
legend('Location', 'best'); xlim([-0.5 7.5]);

% --- Absolute Error Plot ---
error_mag = sqrt((matlab_r - rtl_r').^2 + (matlab_i - rtl_i').^2);

subplot(3, 1, 3);
stem(bins, error_mag, 'k^-', 'LineWidth', 1.5, 'MarkerFaceColor', 'g');
grid on; xlabel('FFT Frequency Bin (k)'); ylabel('Absolute Error');
title('Quantization & Rounding Error |MATLAB - RTL|'); xlim([-0.5 7.5]);

disp('Plots generated successfully!');

% =========================================================================
% STEP 5: Calculate True Hardware SQNR
% =========================================================================
X_ideal_scaled = X_ideal / 8; % 1/8 Scaling for 3 stages

X_ideal_complex = X_ideal_scaled(:);
X_rtl_complex   = (rtl_r(:) + 1i * rtl_i(:));

quant_error = X_ideal_complex - X_rtl_complex;

signal_power = sum(abs(X_ideal_complex).^2);
noise_power  = sum(abs(quant_error).^2);

sqnr_total_db = 10 * log10(signal_power / noise_power);
sqnr_per_bin_db = 10 * log10((abs(X_ideal_complex).^2) ./ (abs(quant_error).^2 + 1e-12));

fprintf('\n===================================================\n');
fprintf('           FFT SQNR ANALYSIS RESULTS               \n');
fprintf('===================================================\n');
fprintf(' Total FFT SQNR: %.2f dB\n', sqnr_total_db);
fprintf('===================================================\n\n');

figure('Name', 'Corrected SQNR Analysis', 'Color', 'w');
stem(0:7, sqnr_per_bin_db, 'm^-', 'LineWidth', 1.5, 'MarkerFaceColor', 'y');
grid on; xlabel('FFT Frequency Bin (k)'); ylabel('SQNR (dB)');
title(sprintf('Corrected SQNR per Bin (Overall SQNR = %.2f dB)', sqnr_total_db));
xlim([-0.5 7.5]);