onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_FFT_16Point/uut/clk
add wave -noupdate /tb_FFT_16Point/uut/enable
add wave -noupdate /tb_FFT_16Point/uut/rst_n
add wave -noupdate /tb_FFT_16Point/uut/s1_i
add wave -noupdate /tb_FFT_16Point/uut/s1_r
add wave -noupdate /tb_FFT_16Point/uut/s2_i
add wave -noupdate /tb_FFT_16Point/uut/s2_r
add wave -noupdate /tb_FFT_16Point/uut/s3_i
add wave -noupdate /tb_FFT_16Point/uut/s3_r
add wave -noupdate /tb_FFT_16Point/uut/W16_0_I
add wave -noupdate /tb_FFT_16Point/uut/W16_0_R
add wave -noupdate /tb_FFT_16Point/uut/W16_1_I
add wave -noupdate /tb_FFT_16Point/uut/W16_1_R
add wave -noupdate /tb_FFT_16Point/uut/W16_2_I
add wave -noupdate /tb_FFT_16Point/uut/W16_2_R
add wave -noupdate /tb_FFT_16Point/uut/W16_3_I
add wave -noupdate /tb_FFT_16Point/uut/W16_3_R
add wave -noupdate /tb_FFT_16Point/uut/W16_4_I
add wave -noupdate /tb_FFT_16Point/uut/W16_4_R
add wave -noupdate /tb_FFT_16Point/uut/W16_5_I
add wave -noupdate /tb_FFT_16Point/uut/W16_5_R
add wave -noupdate /tb_FFT_16Point/uut/W16_6_I
add wave -noupdate /tb_FFT_16Point/uut/W16_6_R
add wave -noupdate /tb_FFT_16Point/uut/W16_7_I
add wave -noupdate /tb_FFT_16Point/uut/W16_7_R
add wave -noupdate /tb_FFT_16Point/uut/X0_i
add wave -noupdate /tb_FFT_16Point/uut/X0_r
add wave -noupdate /tb_FFT_16Point/uut/x0_r
add wave -noupdate /tb_FFT_16Point/uut/X1_i
add wave -noupdate /tb_FFT_16Point/uut/x1_r
add wave -noupdate /tb_FFT_16Point/uut/X1_r
add wave -noupdate /tb_FFT_16Point/uut/X2_i
add wave -noupdate /tb_FFT_16Point/uut/x2_r
add wave -noupdate /tb_FFT_16Point/uut/X2_r
add wave -noupdate /tb_FFT_16Point/uut/X3_i
add wave -noupdate /tb_FFT_16Point/uut/X3_r
add wave -noupdate /tb_FFT_16Point/uut/x3_r
add wave -noupdate /tb_FFT_16Point/uut/X4_i
add wave -noupdate /tb_FFT_16Point/uut/X4_r
add wave -noupdate /tb_FFT_16Point/uut/x4_r
add wave -noupdate /tb_FFT_16Point/uut/X5_i
add wave -noupdate /tb_FFT_16Point/uut/X5_r
add wave -noupdate /tb_FFT_16Point/uut/x5_r
add wave -noupdate /tb_FFT_16Point/uut/X6_i
add wave -noupdate /tb_FFT_16Point/uut/X6_r
add wave -noupdate /tb_FFT_16Point/uut/x6_r
add wave -noupdate /tb_FFT_16Point/uut/X7_i
add wave -noupdate /tb_FFT_16Point/uut/X7_r
add wave -noupdate /tb_FFT_16Point/uut/x7_r
add wave -noupdate /tb_FFT_16Point/uut/X8_i
add wave -noupdate /tb_FFT_16Point/uut/X8_r
add wave -noupdate /tb_FFT_16Point/uut/x8_r
add wave -noupdate /tb_FFT_16Point/uut/X9_i
add wave -noupdate /tb_FFT_16Point/uut/x9_r
add wave -noupdate /tb_FFT_16Point/uut/X9_r
add wave -noupdate /tb_FFT_16Point/uut/X10_i
add wave -noupdate /tb_FFT_16Point/uut/x10_r
add wave -noupdate /tb_FFT_16Point/uut/X10_r
add wave -noupdate /tb_FFT_16Point/uut/X11_i
add wave -noupdate /tb_FFT_16Point/uut/x11_r
add wave -noupdate /tb_FFT_16Point/uut/X11_r
add wave -noupdate /tb_FFT_16Point/uut/X12_i
add wave -noupdate /tb_FFT_16Point/uut/x12_r
add wave -noupdate /tb_FFT_16Point/uut/X12_r
add wave -noupdate /tb_FFT_16Point/uut/X13_i
add wave -noupdate /tb_FFT_16Point/uut/x13_r
add wave -noupdate /tb_FFT_16Point/uut/X13_r
add wave -noupdate /tb_FFT_16Point/uut/X14_i
add wave -noupdate /tb_FFT_16Point/uut/x14_r
add wave -noupdate /tb_FFT_16Point/uut/X14_r
add wave -noupdate /tb_FFT_16Point/uut/X15_i
add wave -noupdate /tb_FFT_16Point/uut/X15_r
add wave -noupdate /tb_FFT_16Point/uut/x15_r
add wave -noupdate /tb_FFT_16Point/uut/ZERO_16
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {65483 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {65050 ps} {66050 ps}
